"""Initial schema

Hand-written to match database/models.py exactly, since alembic/versions/
was empty in the supplied codebase (no `alembic revision --autogenerate`
had ever been run). Verify this against your actual models with
`alembic check` before relying on it in production - it was written by
reading the ORM models, not generated by connecting to a live database
(no network access was available to run alembic autogenerate directly).

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-12
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "investigations",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("status", sa.String(), nullable=False, server_default="in_progress"),
        sa.Column("structured_case", sa.JSON(), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("risk_level", sa.String(), nullable=True),
        sa.Column("final_report", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )

    op.create_table(
        "messages",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "investigation_id",
            sa.String(),
            sa.ForeignKey("investigations.id"),
            nullable=False,
        ),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.create_index("ix_messages_investigation_id", "messages", ["investigation_id"])

    op.create_table(
        "evidence_items",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "investigation_id",
            sa.String(),
            sa.ForeignKey("investigations.id"),
            nullable=False,
        ),
        sa.Column("evidence_type", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("extracted_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.create_index("ix_evidence_items_investigation_id", "evidence_items", ["investigation_id"])

    op.create_table(
        "evidence_records",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "investigation_id",
            sa.String(),
            sa.ForeignKey("investigations.id"),
            nullable=False,
        ),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("authority", sa.String(), nullable=False),
        sa.Column("result", sa.String(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("raw_response", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    op.create_index("ix_evidence_records_investigation_id", "evidence_records", ["investigation_id"])

    op.create_table(
        "fraud_patterns",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False, server_default="Pakistan"),
        sa.Column("pattern", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(), nullable=False, server_default="English"),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("embedding", sa.JSON(), nullable=True),
    )

    op.create_table(
        "banned_agents",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("agent_name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("date_reported", sa.String(), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("banned_agents")
    op.drop_table("fraud_patterns")
    op.drop_index("ix_evidence_records_investigation_id", table_name="evidence_records")
    op.drop_table("evidence_records")
    op.drop_index("ix_evidence_items_investigation_id", table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index("ix_messages_investigation_id", table_name="messages")
    op.drop_table("messages")
    op.drop_table("investigations")
